import React, { createContext, useContext, useState, useEffect } from 'react';
import type { ReactNode } from 'react';

type Language = 'en' | 'hi' | 'bn' | 'te' | 'ta' | 'mr' | 'gu' | 'kn' | 'ml' | 'pa';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Simple translations for demonstration
const translations: Record<Language, Record<string, string>> = {
  en: {
    welcome: 'Welcome back',
    logout: 'Logout',
    login: 'Log in',
    signup: 'Sign up',
    dashboard: 'Dashboard',
    healthSummary: 'Your Health Summary',
    recentActivity: 'Recent Activity',
    medicalHistory: 'Medical History',
    medicalHistoryDesc: 'View and manage your medical records',
    medicalHistoryLong: 'Access your complete medical timeline with saved consultations, reports, and track health progress over time.',
    labReportAnalysis: 'Lab Report Analysis',
    labReportAnalysisDesc: 'Get insights from your lab test results',
    labReportAnalysisLong: 'Upload medical reports and scans to get AI-powered explanations in simple language you can understand.',
    aiDiagnosis: 'AI Diagnosis',
    aiDiagnosisDesc: 'Get preliminary diagnosis based on symptoms',
    aiDiagnosisLong: 'Receive preliminary assessments with probability indicators, suggested precautions, and recommended OTC medicines.',
    mentalHealthChatbot: 'Mental Health Chatbot',
    mentalHealthChatbotDesc: 'Talk to our AI mental health assistant',
    mentalHealthChatbotLong: 'AI-powered chat interface to help with stress, anxiety, and depression with personalized advice and support.',
    telemedicine: 'Telemedicine Integration',
    telemedicineLong: 'Connect with healthcare professionals through secure video calls and share your medical data seamlessly.',
    healthReminders: 'Health Reminders',
    healthRemindersLong: 'Get personalized reminders for medications, appointments, and health check-ups to stay on track with your care plan.',
    featuresHeading: 'Features that',
    empower: 'empower',
    yourHealthJourney: 'your health journey',
    featuresSubheading: 'Clara combines cutting-edge AI technology with user-friendly design to provide comprehensive health support.',
    dashboardReady: 'Your health dashboard is ready. What would you like to do today?',
    healthDataWillAppear: 'Your health data will appear here once you start using Clara\'s features.',
    trackHealthMetrics: 'Track your health metrics, lab results, and get personalized insights.',
    noRecentActivity: 'No recent activity yet.',
    recentInteractions: 'Your recent interactions with Clara will appear here.',
    languageSelector: 'SELECT A LANGUAGE',
    introducing: 'Introducing',
    healthBuddy: 'your health buddy.',
    homeDescription: 'Beautifully designed, intelligent AI medical companion built with',
    homeDescriptionCont: 'modern technology to provide personalized health insights.',
    getStarted: 'Get Started for free',
    meetClara: 'Meet Clara, an AI powered medical companion.',
    healthTagline: 'Understand Your Health. Feel Better, Sooner.',
    backToHome: 'Back to home',
    createAccount: 'Create account',
    enterCredentials: 'Enter your credentials to access your account',
    joinClara: 'Join Clara and start your health journey',
    quickSignIn: 'Quick Sign-In with Mock Account',
    fullName: 'Full Name',
    enterFullName: 'Enter your full name',
    email: 'Email',
    password: 'Password',
    enterPassword: 'Enter your password',
    createPassword: 'Create a password',
    forgotPassword: 'Forgot password?',
    signIn: 'Sign In',
    signingIn: 'Signing In...',
    creatingAccount: 'Creating account...',
    dontHaveAccount: "Don't have an account? ",
    alreadyHaveAccount: "Already have an account? ",
    mockCredentialsNote: 'Mock credentials are pre-filled for testing:',
    orContinueWith: 'Or continue with',
    continueWithGoogle: 'Google'
  },
  hi: {
    welcome: 'वापस स्वागत है',
    logout: 'लॉग आउट',
    login: 'लॉग इन',
    signup: 'साइन अप',
    dashboard: 'डैशबोर्ड',
    healthSummary: 'आपका स्वास्थ्य सारांश',
    recentActivity: 'हाल की गतिविधि',
    medicalHistory: 'चिकित्सा इतिहास',
    medicalHistoryDesc: 'अपने चिकित्सा रिकॉर्ड देखें और प्रबंधित करें',
    medicalHistoryLong: 'सहेजे गए सलाह, रिपोर्ट और समय के साथ स्वास्थ्य प्रगति का एक्सेस करें और ट्रैक करें।',
    labReportAnalysis: 'लैब रिपोर्ट विश्लेषण',
    labReportAnalysisDesc: 'अपने लैब टेस्ट के परिणामों से अंतर्दृष्टि प्राप्त करें',
    labReportAnalysisLong: 'आप समझ सकते हैं कि AI द्वारा उत्पन्न व्याख्या प्राप्त करने के लिए चिकित्सा रिपोर्ट और स्कैन अपलोड करें।',
    aiDiagnosis: 'AI निदान',
    aiDiagnosisDesc: 'लक्षणों के आधार पर प्रारंभिक निदान प्राप्त करें',
    aiDiagnosisLong: 'संभाव्यता सूचक, प्रस्तावित सुगंध और प्रस्तावित OTC दवाओं के साथ प्राथमिक मूल्यांकन प्राप्त करें।',
    mentalHealthChatbot: 'मानसिक स्वास्थ्य चैटबॉट',
    mentalHealthChatbotDesc: 'हमारे एआई मानसिक स्वास्थ्य सहायक से बात करें',
    mentalHealthChatbotLong: 'व्यक्तिगत सलाह और समर्थन के साथ चैट इंटरफेस जो AI द्वारा उत्पन्न होता है जो आपको दोष और उद्वास को कम करने के लिए सलाह देता है।',
    telemedicine: 'टेलीमेडिसिन इंटीग्रेशन',
    telemedicineLong: 'सुरक्षित वीडियो कॉल के माध्यम से स्वास्थ्य सेवा प्रदाताओं के साथ संबद्ध हों और आपके चिकित्सा डेटा अनिवार्य रूप से साझा करें।',
    healthReminders: 'स्वास्थ्य रिमाइन्डर',
    healthRemindersLong: 'आपके यथार्थ योजना के साथ दवाओं, अप्रोटेक्ट और स्वास्थ्य परीक्षण के लिए व्यक्तिगत रिमाइन्डर प्राप्त करें।',
    featuresHeading: 'सुविधाओं के बारे में',
    empower: 'देता है',
    yourHealthJourney: 'आपकी स्वास्थ्य यात्रा',
    featuresSubheading: 'क्लारा बुढ़ापक स्वास्थ्य समर्थन प्रदान करने के लिए अत्याधुनिक AI प्रौद्योगिकी को उपयोगकर्ता-विन्यास डिजाइन के साथ जोड़ती है।',
    dashboardReady: 'आपका स्वास्थ्य डैशबोर्ड तैयार है। आज आप क्या करना चाहेंगे?',
    healthDataWillAppear: 'आपका स्वास्थ्य डेटा यहां दिखाई देगा जब आप क्लारा की सुविधाओं का उपयोग करना शुरू करेंगे।',
    trackHealthMetrics: 'आपके स्वास्थ्य मेट्रिक्स, लैब परिणामों को ट्रैक करें, और व्यक्तिगत अंतर्दृष्टि प्राप्त करें।',
    noRecentActivity: 'अभी तक कोई हालिया गतिविधि नहीं।',
    recentInteractions: 'क्लारा के साथ आपकी हालिया बातचीत यहां दिखाई देगी।',
    languageSelector: 'भाषा चुनें',
    introducing: 'प्रस्तुत है',
    healthBuddy: 'आपका स्वास्थ्य मित्र।',
    homeDescription: 'खूबसूरती से डिज़ाइन किया गया, बुद्धिमान AI मेडिकल साथी',
    homeDescriptionCont: 'व्यक्तिगत स्वास्थ्य अंतर्दृष्टि प्रदान करने के लिए आधुनिक तकनीक।',
    getStarted: 'मुफ्त में शुरू करें',
    meetClara: 'क्लारा से मिलें, एक एआई संचालित मेडिकल साथी।',
    healthTagline: 'अपने स्वास्थ्य को समझें। जल्दी बेहतर महसूस करें।',
    backToHome: 'होम पेज पर वापस जाएं',
    createAccount: 'खाता बनाएं',
    enterCredentials: 'अपने खाते तक पहुंचने के लिए अपना विवरण दर्ज करें',
    joinClara: 'क्लारा से जुड़ें और अपनी स्वास्थ्य यात्रा शुरू करें',
    quickSignIn: 'मॉक अकाउंट से क्विक साइन-इन',
    fullName: 'पूरा नाम',
    enterFullName: 'अपना पूरा नाम दर्ज करें',
    email: 'ईमेल',
    password: 'पासवर्ड',
    enterPassword: 'अपना पासवर्ड डालें',
    createPassword: 'पासवर्ड बनाएं',
    forgotPassword: 'पासवर्ड भूल गए?',
    signIn: 'साइन इन करें',
    signingIn: 'साइन इन हो रहा है...',
    creatingAccount: 'खाता बन रहा है...',
    dontHaveAccount: "खाता नहीं है? ",
    alreadyHaveAccount: "पहले से ही खाता है? ",
    mockCredentialsNote: 'परीक्षण के लिए मॉक क्रेडेंशियल पहले से भरे हुए हैं:',
    orContinueWith: 'या इसके साथ जारी रखें',
    continueWithGoogle: 'गूगल'
  },
  bn: {
    welcome: 'ফিরে স্বাগতম',
    logout: 'লগ আউট',
    login: 'লগ ইন',
    signup: 'সাইন আপ',
    dashboard: 'ড্যাশবোর্ড',
    healthSummary: 'তমারો আরોগ્য সারাংশ',
    recentActivity: 'তাজેতরনી প્র঵ૃত્তি',
    medicalHistory: 'তবીবી ইতিহাস',
    medicalHistoryDesc: 'তমারা তবીবી রেকার্ডોনો জওযা অনુমানીনે অনુমানીনે করো',
    medicalHistoryLong: 'সংরক্ষিত পরামর্শ, রিপোর্ট সহ আপনার সম্পূর্ণ চিকিৎসা সময়রেখা অ্যাক্সেস করুন এবং সময়ের সাথে স্বাস্থ্যের অগ্রগতি ট্র্যাক করুন।',
    labReportAnalysis: 'ল্যাব রিপোর্ট বিশ্লেষণ',
    labReportAnalysisDesc: 'আপনার ল্যাব টেস্টের ফলাফল থেকে অন্তর্দৃষ্টি প্রাপ্ত করুন',
    labReportAnalysisLong: 'সহজ ভাষায় AI-চালিত ব্যাখ্যা পেতে মেডিকেল রিপোর্ট এবং স্ক্যান আপলোড করুন যা আপনি বুঝতে পারেন।',
    aiDiagnosis: 'AI রোগ নির্ণয়',
    aiDiagnosisDesc: 'লক্ষণগুলির আধারে প্রারংভিক নিদান প্রাপ্ত করুন',
    aiDiagnosisLong: 'সম্ভাব্যতা সূচক, প্রস্তাবিত সতর্কতা এবং প্রস্তাবিত OTC ওষুধ সহ প্রাথমিক মূল্যায়ন পান।',
    mentalHealthChatbot: 'মানসিক আরোগ্য চেটবট',
    mentalHealthChatbotDesc: 'আমাদেশ AI মানসিক স্বাস্থ্য সহায়কের সাথে কথা বাতায়ন',
    mentalHealthChatbotLong: 'ব্যক্তিগতকৃত পরামর্শ এবং সমর্থন সহ চাপ, উদ্বেগ এবং বিষণ্ণতা মোকাবেলায় সহায়তা করার জন্য AI-চালিত চ্যাট ইন্টারফেস।',
    telemedicine: 'টেলিমেডিসিন ইন্টিগ্রেশন',
    telemedicineLong: 'সুরক্ষিত ভিডিও কল এর মাধ্যমে স্বাস্থ্যসেবা পেশাদারদের সাথে সংযোগ করুন এবং আপনার মেডিকেল ডেটা নির্বিঘ্নে শেয়ার করুন।',
    healthReminders: 'স্বাস্থ্য রিমাইন্ডার',
    healthRemindersLong: 'আপনার যত্ন পরিকল্পনার সাথে তাল মিলিয়ে থাকার জন্য ওষুধ, অ্যাপয়েন্টমেন্ট এবং স্বাস্থ্য পরীক্ষার জন্য ব্যক্তিগতকৃত রিমাইন্ডার পান।',
    featuresHeading: 'বৈশিষ্ট্য যা',
    empower: 'ক্ষমতায়িত করে',
    yourHealthJourney: 'আপনার স্বাস্থ্য যাত্রা',
    featuresSubheading: 'ক্লারা ব্যাপক স্বাস্থ্য সমর্থন প্রদান করতে অত্যাধুনিক AI প্রযুক্তিকে ব্যবহারকারী-বান্ধব ডিজাইনের সাথে সংযুক্ত করে।',
    dashboardReady: 'আপনার স্বাস্থ্য ড্যাশবোর্ড তয়র হয়। আজ আপনি কি করতে চান?',
    healthDataWillAppear: 'আপনার স্বাস্থ্য ডেটা যখন আপনি ক্লারার বৈধিকতা ব্যবহার শুরু করবেন তখন এখানে দেখানো হবে।',
    trackHealthMetrics: 'আপনার স্বাস্থ্য মেট্রিক্স, ল্যাব ফলাফল ট্র্যাক করুন, এবং ব্যক্তিগত অন্তর্দৃষ্টি প্রাপ্ত করুন।',
    noRecentActivity: 'এখনও কোন সাম্প্রতিক কার্যকলাপ নেই।',
    recentInteractions: 'ক্লারার সাথে আপনার সাম্প্রতিক কার্যকলাপ এখানে দেখানো হবে।',
    languageSelector: 'একটি ভাষা নির্বাচন করুন',
    introducing: 'পরিচয় করিয়ে দেওয়া হচ্ছে',
    healthBuddy: 'আপনার স্বাস্থ্য বন্ধু।',
    homeDescription: 'সুন্দরভাবে ডিজাইন করা, বুদ্ধিমান AI মেডিকেল সঙ্গী',
    homeDescriptionCont: 'ব্যক্তিগত স্বাস্থ্য অন্তর্দৃষ্টি প্রদান করতে আধুনিক প্রযুক্তি।',
    getStarted: 'বিনামূল্যে শুরু করুন',
    meetClara: 'ক্লারার সাথে দেখা করুন, একটি AI চালিত মেডিকেল সঙ্গী।',
    healthTagline: 'আপনার স্বাস্থ্য বুঝুন। আরও ভালো বোধ করুন, শীঘ্রই।',
    backToHome: 'হোম পেজে ফিরে যান',
    createAccount: 'খাতা বনায়ন',
    enterCredentials: 'অপনার খাতা তক পহাচনের জন্য অপনার বিবরণ দরজ করুন',
    joinClara: 'ক্লারা সহয়ে এবং আপনার স্বাস্থ্য যাত্রা শুরু করুন',
    quickSignIn: 'মাক অকাউন্ট সহয়ে কুইক সাইন-ইন',
    fullName: 'পূরা নাম',
    enterFullName: 'অপনার পূরা নাম দরজ করুন',
    email: 'ইমেল',
    password: 'পাস঵র্ড',
    enterPassword: 'অপনার পাস঵র্ড ডালন',
    createPassword: 'পাস঵র্ড বনায়ন',
    forgotPassword: 'পাস঵র্ড ভুল গএ?',
    signIn: 'সাইন ইন করুন',
    signingIn: 'সাইন ইন হয় রহায়...',
    creatingAccount: 'খাতা বনায়ন রহায়...',
    dontHaveAccount: "খাতা নহয়? ",
    alreadyHaveAccount: "পুরুষ হয় খাতা? ",
    mockCredentialsNote: 'পরিক্ষণ জন্য মাক ক্রেডেনশিয়াল পুরুষ হয় ভরায়ন:',
    orContinueWith: 'অথবা এই সহয়ে থাকা',
    continueWithGoogle: 'গুগল'
  },
  te: {
    welcome: 'తిరిగి స్వాగతం',
    logout: 'లాగ్ అవుట్',
    login: 'లాగిన్',
    signup: 'సైన్ అప్',
    dashboard: 'డాష్‌బోర్డ్',
    healthSummary: 'మీ ఆరోగ్య సారాంశం',
    recentActivity: 'ఇటీవలి కార్యాచరణ',
    medicalHistory: 'వైద్య చరిత్ర',
    medicalHistoryDesc: 'మీ వైద్య రికార్డ్లను చూడండి మరియు ప్రబంధించండి',
    labReportAnalysis: 'ల్యాబ్ నివేదిక విశ్లేషణ',
    labReportAnalysisDesc: 'మీ ల్యాబ్ టెస్ట్ ఫలాల నుండి అంతర్దృష్టి పొందండి',
    aiDiagnosis: 'AI నిర్ధారణ',
    aiDiagnosisDesc: 'లక్షణాల ఆధారంగా ప్రారంభిక నిదానం పొందండి',
    mentalHealthChatbot: 'మానసిక ఆరోగ్య చాట్‌బాట్',
    mentalHealthChatbotDesc: 'మామూలు AI మానసిక స్వాస్థ్య సహాయకతో చాట్లు',
    dashboardReady: 'మీ స్వాస్థ్య డాష్బోర్డ్ ప్రస్తుతం అయింది. ఇటువంటి ప్రయోగాలు చేయాల్సి అనుమానించండి',
    languageSelector: 'భాషను ఎంచుకోండి',
    introducing: 'పరిచయం చేస్తోంది',
    healthBuddy: 'మీ ఆరోగ్య మిత్రుడు.',
    homeDescription: 'అందంగా రూపొందించబడిన, తెలివైన AI వైద్య సహచరుడు',
    homeDescriptionCont: 'వ్యక్తిగతీకరించిన ఆరోగ్య అంతర్దృష్టులను అందించడానికి ఆధునిక సాంకేతికత.',
    getStarted: 'ఉచితంగా ప్రారంభించండి',
    meetClara: 'క్లారాను కలవండి, AI ఆధారిత మెడిక్ల్ కంపానియన్.',
    healthTagline: 'మీ ఆరోగ్యాన్ని అర్థం చేసుకోండి. త్వరగా మెరుగ్గా ఫీల్ అవ్వండి.',
    backToHome: 'హోమ్‌కి తిరిగి వెళ్ళండి',
  },
  ta: {
    welcome: 'மீண்டும் வரவேற்கிறோம்',
    logout: 'வெளியேறு',
    login: 'உள்நுழைய',
    signup: 'பதிவு செய்ய',
    dashboard: 'டாஷ்போர்டு',
    healthSummary: 'உங்கள் ஆரோக்கிய சுருக்கம்',
    recentActivity: 'சமீபத்திய செயல்பாடு',
    medicalHistory: 'மருத்துவ வரலாறு',
    medicalHistoryDesc: 'உங்கள் மருத்துவ பதிவுகளைப் பார்க்கவும் மற்றும் நிர்வகிக்கவும்',
    labReportAnalysis: 'ல்யாப் ரிபோர்ட் விளக்கம்',
    aiDiagnosis: 'AI ரோ஗நிர்ணயம்',
    mentalHealthChatbot: 'மன ஆரோக்கிய சேட்போட்',
    languageSelector: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    introducing: 'அறிமுகப்படுத்துகிறது',
    healthBuddy: 'உங்கள் ஆரோக்கிய நண்பர்.',
    homeDescription: 'அழகாக வடிவமைக்கப்பட்ட, புத்திசாலித்தனமான AI மருத்துவ துணை',
    homeDescriptionCont: 'தனிப்பயனாக்கப்பட்ட ஆரோக்கிய நுண்ணறிவுகளை வழங்க நவீன தொழில்நுட்பம்.',
    getStarted: 'இலவசமாக தொடங்கவும்',
    meetClara: 'கிளாராவைச் சந்திக்கவும், ஒரு AI இயக்கப்படும் மருத்துவ துணை.',
    healthTagline: 'உங்கள் ஆரோக்கியத்தைப் புரிந்துகொள்ளுங்கள். விரைவில் சிறப்பாக உணருங்கள்.',
    backToHome: 'முகப்புப்பக்கத்திற்குத் திரும்பவும்',
  },
  mr: {
    welcome: 'पुन्हा स्वागत आहे',
    logout: 'लॉग आउट',
    login: 'लॉग इन',
    signup: 'साइन अप',
    dashboard: 'डॅशबोर्ड',
    healthSummary: 'तुमचा आरोग्य सारांश',
    recentActivity: 'अलीकडील क्रियाकलाप',
    medicalHistory: 'वैद्यकीय इतिहास',
    labReportAnalysis: 'लॅब अहवाल विश्लेषण',
    aiDiagnosis: 'AI निदान',
    mentalHealthChatbot: 'मानसिक आरोग्य चॅटबॉट',
    languageSelector: 'एक भाषा निवडा',
    introducing: 'सादर करत आहे',
    healthBuddy: 'तुमचा आरोग्य मित्र.',
    homeDescription: 'सुंदर डिझाइन केलेला, बुद्धिमान AI मेडिकल सहकारी',
    homeDescriptionCont: 'वैयक्तिकृत आरोग्य अंतर्ज्ञान प्रदान करण्यासाठी आधुनिक तंत्रज्ञान.',
    getStarted: 'मोफत सुरू करा',
    meetClara: 'क्लारा भेटा, एक AI चालित मेडिकल सहकारी.',
    healthTagline: 'तुमचे आरोग्य समजून घ्या. लवकर बरे वाटेल.',
    backToHome: 'मुखपृष्ठावर परत या',
  },
  gu: {
    welcome: 'પાછા આવ્યા સ્વાગત છે',
    logout: 'લૉગ આઉટ',
    login: 'લોગ ઇન',
    signup: 'સાઇન અપ',
    dashboard: 'ડેશબોર્ડ',
    healthSummary: 'તમારો આરોગ્ય સારાંશ',
    recentActivity: 'તાજેતરની પ્રવૃત્તિ',
    medicalHistory: 'તબીબી ઇતિહાસ',
    labReportAnalysis: 'લેબ રિપોર્ટ વ્યશ્લેષણ',
    aiDiagnosis: 'AI નિદાન',
    mentalHealthChatbot: 'માનસિક આરોગ્ય ચેટબોટ',
    languageSelector: 'ભાષા પસંદ કરો',
    introducing: 'રજૂ કરી રહ્યા છીએ',
    healthBuddy: 'તમારા આરોગ્યના મિત્ર.',
    homeDescription: 'સુંદર રીતે ડિઝાઇન કરેલ, બુદ્ધિશાળી AI મેડિકલ સાથી',
    homeDescriptionCont: 'વ્યક્તિગત આરોગ્ય અંતર્દૃષ્ટિ પ્રદાન કરવા માટે આધુનિક ટેકનોલોજી.',
    getStarted: 'મફતમાં શરૂ કરો',
    meetClara: 'ક્લારાને મળો, એક AI સંચાલિત મેડિકલ સાથી.',
    healthTagline: 'તમારા આરોગ્યને સમજો. જલદી સારું અનુભવો.',
    backToHome: 'હોમ પેજ પર પાછા જાઓ',
  },
  kn: {
    welcome: 'ಮತ್ತೆ ಸ್ವಾಗತ',
    logout: 'ಲಾಗ್ ಔಟ್',
    login: 'ಲಾಗಿನ್',
    signup: 'ಸೈನ್ ಅಪ್',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    healthSummary: 'ನಿಮ್ಮ ಆರೋಗ್ಯ ಸಾರಾಂಶ',
    recentActivity: 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
    medicalHistory: 'ವೈದ್ಯಕೀಯ ಇತಿಹಾಸ',
    labReportAnalysis: 'ಲ್ಯಾಬ್ ವರದಿ ವಿಶ್ಲೇಷಣೆ',
    aiDiagnosis: 'AI ರೋಗನಿರ್ಣಯ',
    mentalHealthChatbot: 'ಮಾನಸಿಕ ಆರೋಗ್ಯ ಚಾಟ್‌ಬಾಟ್',
    languageSelector: 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    introducing: 'ಪರಿಚಯಿಸುತ್ತಿದೆ',
    healthBuddy: 'ನಿಮ್ಮ ಆರೋಗ್ಯ ಗೆಳೆಯ.',
    homeDescription: 'ಸುಂದರವಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಲಾದ, ಬುದ್ಧಿವಂತ AI ವೈದ್ಯಕೀಯ ಸಹಚರ',
    homeDescriptionCont: 'ವೈಯಕ್ತಿಕ ಆರೋಗ್ಯ ಒಳನೋಟಗಳನ್ನು ಒದಗಿಸಲು ಆಧುನಿಕ ತಂತ್ರಜ್ಞಾನ.',
    getStarted: 'ಉಚಿತವಾಗಿ ಪ್ರಾರಂಭಿಸಿ',
    meetClara: 'ಕ್ಲಾರಾ ಭೇಟಿ ಮಾಡಿ, ಎಐ ಶಕ್ತಿಯುತ ವೈದ್ಯಕೀಯ ಸಂಗಾತಿ.',
    healthTagline: 'ನಿಮ್ಮ ಆರೋಗ್ಯವನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ. ಬೇಗನೆ ಚೆನ್ನಾಗಿ ಭಾವಿಸಿ.',
    backToHome: 'ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ',
  },
  ml: {
    welcome: 'തിരികെ സ്വാഗതം',
    logout: 'ലോഗൗട്ട്',
    login: 'ലോഗിൻ',
    signup: 'സൈൻ അപ്പ്',
    dashboard: 'ഡാഷ്ബോർഡ്',
    healthSummary: 'നിങ്ങളുടെ ആരോഗ്യ സംഗ്രഹം',
    recentActivity: 'സമീപകാല പ്രവർത്തനം',
    medicalHistory: 'മെഡിക്കൽ ചരിത്രം',
    labReportAnalysis: 'ലാബ് റിപ്പോർട്ട് വിശകലനം',
    aiDiagnosis: 'AI രോഗനിർണ്ണയം',
    mentalHealthChatbot: 'മാനസിക ആരോഗ്യ ചാറ്റ്ബോട്ട്',
    languageSelector: 'ഒരു ഭാഷ തിരഞ്ഞെടുക്കുക',
    introducing: 'പരിചയപ്പെടുത്തുന്നു',
    healthBuddy: 'നിങ്ങളുടെ ആരോഗ്യ സുഹൃത്ത്.',
    homeDescription: 'മനോഹരമായി രൂപകൽപ്പന ചെയ്ത, ബുദ്ധിമാനായ AI മെഡിക്കൽ കൂട്ടാളി',
    homeDescriptionCont: 'വ്യക്തിഗത ആരോഗ്യ ഉൾക്കാഴ്ചകൾ നൽകാൻ ആധുനിക സാങ്കേതികവിദ്യ.',
    getStarted: 'സൗജന്യമായി ആരംഭിക്കുക',
    meetClara: 'ക്ലാറയെ കാണുക, AI പ്രവർത്തിക്കുന്ന മെഡിക്കൽ സഹായി.',
    healthTagline: 'നിങ്ങളുടെ ആരോഗ്യം മനസ്സിലാക്കുക. വേഗത്തിൽ നന്നായി തോന്നുക.',
    backToHome: 'ഹോം പേജിലേക്ക് മടങ്ങുക',
  },
  pa: {
    welcome: "ਵਾਪਸ ਆਉਣ 'ਤੇ ਸਵਾਗਤ ਹੈ",
    logout: 'ਲੌਗ ਆਊਟ',
    login: 'ਲਾਗ ਇਨ',
    signup: 'ਸਾਈਨ ਅੱਪ',
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    healthSummary: 'ਤੁਹਾਡਾ ਸਿਹਤ ਸਾਰ',
    recentActivity: 'ਹਾਲੀਆ ਗਤੀਵਿਧੀ',
    medicalHistory: 'ਮੈਡੀਕਲ ਇਤਿਹਾਸ',
    labReportAnalysis: 'ਲੈਬ ਰਿਪੋਰਟ ਵਿਸ਼ਲੇਸ਼ਣ',
    aiDiagnosis: 'AI ਨਿਦਾਨ',
    mentalHealthChatbot: 'ਮਾਨਸਿਕ ਸਿਹਤ ਚੈਟਬੋਟ',
    languageSelector: 'ਇੱਕ ਭਾਸ਼ਾ ਚੁਣੋ',
    introducing: 'ਪੇਸ਼ ਕਰ ਰਹੇ ਹਾਂ',
    healthBuddy: 'ਤੁਹਾਡਾ ਸਿਹਤ ਸਹਾਇਕ.',
    homeDescription: 'ਖੂਬਸੂਰਤੀ ਨਾਲ ਡਿਜ਼ਾਈਨ ਕੀਤਾ, ਬੁੱਧੀਮਾਨ AI ਮੈਡੀਕਲ ਸਾਥੀ',
    homeDescriptionCont: 'ਨਿੱਜੀ ਸਿਹਤ ਅੰਤਰਦ੍ਰਿਸ਼ਟੀ ਪ੍ਰਦਾਨ ਕਰਨ ਲਈ ਆਧੁਨਿਕ ਤਕਨਾਲੋਜੀ.',
    getStarted: 'ਮੁਫ਼ਤ ਵਿੱਚ ਸ਼ੁਰੂ ਕਰੋ',
    meetClara: 'ਕਲਾਰਾ ਨੂੰ ਮਿਲੋ, ਇੱਕ AI ਸੰਚਾਲਿਤ ਮੈਡੀਕਲ ਸਾਥੀ.',
    healthTagline: 'ਆਪਣੀ ਸਿਹਤ ਨੂੰ ਸਮਝੋ। ਜਲਦੀ ਬਿਹਤਰ ਮਹਿਸੂਸ ਕਰੋ।',
    backToHome: "ਹੋਮ ਪੇਜ 'ਤੇ ਵਾਪਸ ਜਾਓ",
  },
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  // Get language from localStorage or default to English
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  // Update localStorage when language changes
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  // Translation function
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  // Apply HTML lang attribute
  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 